### ISSUE TITLE
"No storage option exists to persist the session" error with Supabase

### ISSUE THREAD

**Issue by johnbrownlow** [jorge-menjivar/unSAGED#15]
Getting the following error when running locally:

_No storage option exists to persist the session, which may result in unexpected behavior when using auth.
        If you want to set persistSession to true, please provide a storage option or you may set persistSession to false to disable this warning_

**Comment by johnbrownlow** [comment]
Still getting this error with the fix for some reason (after npm ci to clean everything up)

**Comment by jorge-menjivar** [comment]
Will look more into this. This is just a warning though. It should not affect the app as we are not relying on supabase auth. We use nextauth instead.

**Comment by Jmackles** [comment]
> Will look more into this. This is just a warning though. It should not affect the app as we are not relying on supabase auth. We use nextauth instead.

This issue is persisting with me, and I cannot proceed past, so this is definitely more than a warning. I also receive the same error.

`No storage option exists to persist the session, which may result in unexpected behavior when using auth.
        If you want to set persistSession to true, please provide a storage option or you may set persistSession to false to disable this warning.
No storage option exists to persist the session, which may result in unexpected behavior when using auth.
        If you want to set persistSession to true, please provide a storage option or you may set persistSession to false to disable this warning.
[next-auth][warn][NEXTAUTH_URL]
https://next-auth.js.org/warnings#nextauth_url`

Going into the localhost takes me to a signin screen with nothing on it. I'm sure there is likely some user error afoot but I feel confident that I followed the readme pretty faithfully. I'm literally unable to proceed to even try the features. 😬 
![signinthing](https://github.com/jorge-menjivar/unSAGED/assets/124995231/b9455b9e-687c-46e5-b69a-a34ea762648f)

**Comment by jorge-menjivar** [comment]
@Jmackles That happens because you don’t have any auth providers configured. Once you have auth providers configured they will start populating there. Ideally we would want a warning of some kind to show up and let you know about this, I just haven't gotten the chance to do it yet.

**Comment by JPDucky** [comment]
I am receiving this same error, with the same localhost behavior and I *do* have auth providers configured. I'll continue testing to see if I can narrow something down

**Comment by JPDucky** [comment]
Behavior remains unchanged when setting `NODE_ENV` to `production` as well.

**Comment by dino1729** [comment]
I have the same issue with github and google auth providers. Any help would be appreciated.

**Comment by jorge-menjivar** [comment]
#34 Fixes this
