### ISSUE TITLE
Corrupted database after attempting to import from Chabotui.com

### ISSUE THREAD

**Issue by johnbrownlow** [jorge-menjivar/unSAGED#19]
I imported a json that I had exported from chatbotui.com, but the app now throws this error when run

<img width="1009" alt="Screenshot 2023-07-12 at 7 37 35 AM" src="https://github.com/jorge-menjivar/unSAGED/assets/13790247/17a9e62a-14d4-4faa-9eae-1b3c726b3e04">

**Comment by johnbrownlow** [comment]
(This is now a showstopper as I don't know how to fix it without rebuilding the whole thing including the database)

**Comment by johnbrownlow** [comment]
Okay, mark this as solved.

The readme suggests that NEXTAUTH_URL has a default value, ie doesn't have to be set, but in fact it must be set when running locally. I had commented it out.

**Comment by jorge-menjivar** [comment]
@johnbrownlow check this branch: https://github.com/jorge-menjivar/unSAGED/tree/import-fix

Let me know if this solves the issues

**Comment by johnbrownlow** [comment]
Yes! That solved it. Thank you!

**Comment by jorge-menjivar** [comment]
> I notice that it doesn't import system prompts. Is this because ChatbotUI doesn't export them?

Chatbot UI doesn’t have support for system prompts at all. Their “prompts”, are imported as message templates.

There are some caveats to have in mind as well. Importing the same file twice will result in duplicate messages because chatbot UI doesn’t include message IDs or timestamps, so there is no easy way of telling which messages have already been imported. I guess we could go message by message comparing the content to find the difference and make a guess what messages the user would like to import, but that’s out scope for now.

**Comment by johnbrownlow** [comment]
It works fine for me right now as I'm just using it to transition. Cheers!
