### ISSUE TITLE
Access to other model params?

### ISSUE THREAD

**Issue by Boscop** [jorge-menjivar/unSAGED#61]
Would it be possible to add these model parameter options as well? (Currently it seems to only expose the temperature setting.)

<img width="508" alt="image" src="https://github.com/jorge-menjivar/unSAGED/assets/535593/753f8b76-e1a5-465f-8b6a-44b3ece5628f">

**Comment by jorge-menjivar** [comment]
Yes, I would like to add all of these soon. I am personally mostly interested in the newly introduced seed parameter. It should be one of the very next things I work on. The main issue with doing this is that it would require a postgres table change to store this data, so I will need to be extra careful. Instead of creating one column per parameter as we have done so far, we would probably want to want a single parameters JSONB column that can flexibly support different parameters across different models without having to change the database any further.

**Comment by jorge-menjivar** [comment]
Here is  my work on this: https://github.com/jorge-menjivar/unSAGED/tree/model-params-upgrade#-upgrading-unsaged

I will be moving it to the main branch if everything goes well. Could you give it a try if you can?

**Comment by jorge-menjivar** [comment]
@KyleRobertsAI yes, I will add that

**Comment by jorge-menjivar** [comment]
@KyleRobertsAI I added that into the new branch. Check the sample env file for the list of supported env variables. We need to create a proper documentation site because the README is already way too long and hard to work with. I will skip adding them there for now and just update them once we have a documentation site up.
